# Docs: https://git.io/JCUAY
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "asoul-go/core"
    commit-message:
      prefix: "mod:"
