version: '3'

tasks:
  web:
    desc: Build the binary and start the web server
    deps: [build]
    cmds:
      - ./asouldocs web

  build:
    desc: Build the binary
    cmds:
      - go build -v
        -ldflags '
        -X "{{.PKG_PATH}}.BuildTime={{.BUILD_TIME}}"
        -X "{{.PKG_PATH}}.BuildCommit={{.BUILD_COMMIT}}"
        '
        -trimpath -o asouldocs
    vars:
      PKG_PATH: github.com/asoul-sig/asouldocs/internal/conf
      BUILD_TIME:
        sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
      BUILD_COMMIT:
        sh: git rev-parse HEAD
    sources:
      - main.go
      - internal/**/*.go
      - conf/**/*
      - public/**/*
      - templates/**/*

  clean:
    desc: Cleans up system meta files
    cmds:
      - find . -name "*.DS_Store" -type f -delete

  release:
    desc: Build the binaries and pack resources to ZIP archives
    cmds:
      - env GOOS=darwin GOARCH=amd64 go build -o asouldocs; tar czf darwin_amd64.tar.gz asouldocs
      - env GOOS=linux GOARCH=amd64 go build -o asouldocs; tar czf linux_amd64.tar.gz asouldocs
      - env GOOS=linux GOARCH=386 go build -o asouldocs; tar czf linux_386.tar.gz asouldocs
      - env GOOS=linux GOARCH=arm go build -o asouldocs; tar czf linux_arm.tar.gz asouldocs
      - env GOOS=windows GOARCH=amd64 go build -o asouldocs.exe; tar czf windows_amd64.tar.gz asouldocs
      - env GOOS=windows GOARCH=386 go build -o asouldocs.exe; tar czf windows_386.tar.gz asouldocs
